// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addFeed = `-- name: AddFeed :one
INSERT INTO gator.feeds (created_at, updated_at, name, url, added_by)
VALUES (NOW(),
        NOW(),
        $1,
        $2,
        $3
)
RETURNING id, created_at, updated_at, name, url, added_by
`

type AddFeedParams struct {
	Name    string
	Url     sql.NullString
	AddedBy uuid.NullUUID
}

func (q *Queries) AddFeed(ctx context.Context, arg AddFeedParams) (GatorFeed, error) {
	row := q.db.QueryRowContext(ctx, addFeed, arg.Name, arg.Url, arg.AddedBy)
	var i GatorFeed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.AddedBy,
	)
	return i, err
}
